### ISSUE TITLE
syntax error on install

### ISSUE THREAD

**Issue by sliptonic** [wishtack/gitbook-printer#4]
Hi.  I don't know npm very well so I'm afraid I can't give much insight beyond the error message.  Here's what I'm seeing:

brad@makerbob ~/Dropbox/bookwiki/.gitbook/assets $ sudo npm install -g @wishtack/gitbook-printer
/usr/local/lib/node_modules/npm/bin/npm-cli.js:79
      let notifier = require('update-notifier')({pkg})
      ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
brad@makerbob ~/Dropbox/bookwiki/.gitbook/assets $

**Comment by yjaaidi** [comment]
Hi @sliptonic,

Thank you for your feedback. Could you please try to update your NodeJS version. Version 10 should be perfect.

Hope it helps.
